# /*
# *	Filename		:	pubspec.yaml
# *	Purpose			:	
# * Created			: 2019-06-04 16:35:03 by Detective Conan
# *	Updated			:	2019-10-28 09:25:03 by Detective Conan
# *	Changes			:   Changed the version
# */

name: mt_carmel_app
description: Mobile App for Mount Carmel Basilica

version: 1.0.1+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences:  any # ^0.5.2+1
#  http: ^0.12.0+2
#  dio: ^3.0.3
  dio_http_cache: ^0.2.0
  dio_http2_adapter: ^1.0.0
  json_annotation: ^3.0.0
  transformer_page_view: ^0.1.6

  share: ^0.6.2+3
  table_calendar: ^1.2.2
#  rxdart: ^0.22.0

  google_maps_flutter: ^0.5.21

  # flutter_html_view: ^0.5.11
  flutter_html_textview_render: ^0.1.3
  html2md: ^0.3.1

#  video_player: ^0.10.1+3

#  youtube_player_flutter: ^2.0.0
  youtube_player_flutter: ^4.1.0

#  cached_network_image: ^1.0.0
  flutter_advanced_networkimage: ^0.5.0

  # permission: ^0.1.2
  permission_handler: ^3.1.0

#  bloc: ^0.15.0
  password: ^1.0.0
#  connectivity: ^0.4.3+2
  data_connection_checker: ^0.3.4
  get_it: ^1.0.3+2
  equatable: ^0.2.6
  flutter_bloc: ^0.21.0
  flutter_form_builder: ^3.2.8
  image_picker: ^0.6.0+17

  flutter_datetime_picker: ^1.2.5

  provider: ^3.1.0


dev_dependencies:
#  test: ^1.9.1
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: 3.2.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"


flutter:
  assets:
    - assets/images/mt_carmel_logo.png
  
  fonts:
  - family: Helvetica
    fonts:
      - asset: assets/fonts/Helvetica/Normal/Helvetica-normal.ttf
      - asset: assets/fonts/Helvetica/Bold/Helvetica-Bold.otf
        style: italic

  - family: MountCarmel
    fonts:
      - asset: assets/fonts/icons/MountCarmel.ttf
        weight: 400
        
  uses-material-design: true
    