# /*
# *	Filename		:	pubspec.yaml
# *	Purpose			:	
# * Created			: 2019-06-04 16:35:03 by Detective Conan
# *	Updated			:	2019-06-04 16:35:03 by Detective Conan 
# *	Changes			:
# */

name: mt_carmel_app
description: Mobile App for Mount Carmel Basilica

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences:  any # ^0.5.2+1
  http: ^0.12.0+2
  json_annotation: ^2.4.0
  transformer_page_view: ^0.1.6

  share: ^0.6.1
  table_calendar: ^1.2.2
  rxdart: ^0.22.0

  google_maps_flutter: ^0.5.16

  # flutter_html_view: ^0.5.11
  flutter_html_textview_render: ^0.1.3

#  video_player: ^0.10.1+3

  youtube_player_flutter: ^2.0.0
  

  # permission: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.0.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"


flutter:
  assets:
    - assets/images/mt_carmel_logo.png
    - assets/images/sample_user.png
  
  fonts:
  - family: Helvetica
    fonts:
      - asset: assets/fonts/Helvetica/Normal/helvetica-normal.ttf
      - asset: assets/fonts/Helvetica/Bold/Helvetica-Bold.otf
        style: italic

  - family: MountCarmel
    fonts:
      - asset: assets/fonts/icons/MountCarmel.ttf
        weight: 400
        
  uses-material-design: true
    