// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'marriage.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Marriage _$MarriageFromJson(Map<String, dynamic> json) {
  return Marriage(
    json['id'],
    json['with_previous_marriage'],
    json['is_anyone_an_ofw'],
    json['living_abroad'],
    json['is_widower'],
    json['groom_name'],
    json['groom_nickname'],
    json['groom_dt_birth'],
    json['groom_birth_place'],
    json['groom_religion_id'],
    json['groom_religion_name'],
    json['groom_occupation'],
    json['groom_work_place'],
    json['groom_nationality_id'],
    json['groom_nationality_name'],
    json['groom_landline'],
    json['groom_mobile'],
    json['groom_email'],
    json['groom_address_1'],
    json['groom_address_2'],
    json['groom_city'],
    json['groom_province'],
    json['groom_country'],
    json['groom_parish_name'],
    json['groom_parish_address'],
    json['groom_provincial_address'],
    json['groom_father_name'],
    json['groom_father_nationality_id'],
    json['groom_father_nationality_name'],
    json['groom_mother_name'],
    json['groom_mother_nationality_id'],
    json['groom_mother_nationality_name'],
    json['bride_name'],
    json['bride_nickname'],
    json['bride_dt_birth'],
    json['bride_birth_place'],
    json['bride_religion_id'],
    json['bride_religion_name'],
    json['bride_occupation'],
    json['bride_work_place'],
    json['bride_nationality_id'],
    json['bride_nationality_name'],
    json['bride_landline'],
    json['bride_mobile'],
    json['bride_email'],
    json['bride_address_1'],
    json['bride_address_2'],
    json['bride_city'],
    json['bride_province'],
    json['bride_country'],
    json['bride_parish_name'],
    json['bride_parish_address'],
    json['bride_provincial_address'],
    json['bride_father_name'],
    json['bride_father_nationality_id'],
    json['bride_father_nationality_name'],
    json['bride_mother_name'],
    json['bride_mother_nationality_id'],
    json['bride_mother_nationality_name'],
    json['sponsors_name'],
    json['sponsors_age'],
    json['sponsors_landline'],
    json['sponsors_mobile'],
    json['sponsors_address'],
    json['name_contact_person'],
    json['landline_contact_person'],
    json['mobile_contact_person'],
    json['status_id'],
    json['status_name'],
    json['dt_created'],
    json['dt_updated'],
    json['created_by'],
    json['updated_by'],
  );
}

Map<String, dynamic> _$MarriageToJson(Marriage instance) => <String, dynamic>{
      'id': instance.id,
      'with_previous_marriage': instance.withPreviousMarriage,
      'is_anyone_an_ofw': instance.isAnyoneAnOfw,
      'living_abroad': instance.livingAbroad,
      'is_widower': instance.isWidower,
      'groom_name': instance.groomName,
      'groom_nickname': instance.groomNickname,
      'groom_dt_birth': instance.groomDtBirth,
      'groom_birth_place': instance.groomBirthPlace,
      'groom_religion_id': instance.groomReligionId,
      'groom_religion_name': instance.groomReligionName,
      'groom_occupation': instance.groomOccupation,
      'groom_work_place': instance.groomWorkPlace,
      'groom_nationality_id': instance.groomNationalityId,
      'groom_nationality_name': instance.groomNationalityName,
      'groom_landline': instance.groomLandline,
      'groom_mobile': instance.groomMobile,
      'groom_email': instance.groomEmail,
      'groom_address_1': instance.groomAddress1,
      'groom_address_2': instance.groomAddress2,
      'groom_city': instance.groomCity,
      'groom_province': instance.groomProvince,
      'groom_country': instance.groomCountry,
      'groom_parish_name': instance.groomParishName,
      'groom_parish_address': instance.groomParishAddress,
      'groom_provincial_address': instance.groomProvincialAddress,
      'groom_father_name': instance.groomFatherName,
      'groom_father_nationality_id': instance.groomFatherNationalityId,
      'groom_father_nationality_name': instance.groomFatherNationalityName,
      'groom_mother_name': instance.groomMotherName,
      'groom_mother_nationality_id': instance.groomMotherNationalityId,
      'groom_mother_nationality_name': instance.groomMotherNationalityName,
      'bride_name': instance.brideName,
      'bride_nickname': instance.brideNickname,
      'bride_dt_birth': instance.brideDtBirth,
      'bride_birth_place': instance.brideBirthPlace,
      'bride_religion_id': instance.brideReligionId,
      'bride_religion_name': instance.brideReligionName,
      'bride_occupation': instance.brideOccupation,
      'bride_work_place': instance.brideWorkPlace,
      'bride_nationality_id': instance.brideNationalityId,
      'bride_nationality_name': instance.brideNationalityName,
      'bride_landline': instance.brideLandline,
      'bride_mobile': instance.brideMobile,
      'bride_email': instance.brideEmail,
      'bride_address_1': instance.brideAddress1,
      'bride_address_2': instance.brideAddress2,
      'bride_city': instance.brideCity,
      'bride_province': instance.brideProvince,
      'bride_country': instance.brideCountry,
      'bride_parish_name': instance.brideParishName,
      'bride_parish_address': instance.brideParishAddress,
      'bride_provincial_address': instance.brideProvincialAddress,
      'bride_father_name': instance.brideFatherName,
      'bride_father_nationality_id': instance.brideFatherNationalityId,
      'bride_father_nationality_name': instance.brideFatherNationalityName,
      'bride_mother_name': instance.brideMotherName,
      'bride_mother_nationality_id': instance.brideMotherNationalityId,
      'bride_mother_nationality_name': instance.brideMotherNationalityName,
      'sponsors_name': instance.sponsorsName,
      'sponsors_age': instance.sponsorsAge,
      'sponsors_landline': instance.sponsorsLandline,
      'sponsors_mobile': instance.sponsorsMobile,
      'sponsors_address': instance.sponsorsAddress,
      'name_contact_person': instance.nameContactPerson,
      'landline_contact_person': instance.landlineContactPerson,
      'mobile_contact_person': instance.mobileContactPerson,
      'status_id': instance.statusId,
      'status_name': instance.statusName,
      'dt_created': instance.dtCreated,
      'dt_updated': instance.dtUpdated,
      'created_by': instance.createdBy,
      'updated_by': instance.updatedBy,
    };
