/// Flutter icons MountCarmel
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MountCarmelIcons
///      fonts:
///       - asset: fonts/MountCarmel.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MountCarmelIcons {
  MountCarmelIcons._();

  static const _kFontFam = 'MountCarmel';

  static const IconData baptism = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData borderedlogo = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData communion = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData confirmation = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData events = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData joinus = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData logo = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData makearequest = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData management = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData marriage = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData mytransactions = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData passing = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData profile = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData refresh = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData sendhelp = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData services = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData thankyou = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData transparency = const IconData(0xe814, fontFamily: _kFontFam);
}
